var avatar =
"https://scontent.fhan3-3.fna.fbcdn.net/v/t1.18169-9/11202575_1059472474071329_1479616494666683147_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=dd63ad&_nc_ohc=i4OoxBgRiLAAX8kwdCt&_nc_ht=scontent.fhan3-3.fna&oh=00_AfDKgUBB6dku0MtSojN4AKD9BurbB2IvaQL_OUfowkhtKg&oe=65B45EA9";
var introduce = 
"Fullname: Dinh Hoang Viet.Birth: 21-05.Email: dinhviet34@gmail(com).I am an information technology engineer.I have many years experience of C# dotnet.I also know that Reactjs, React Native, and Javascript certainly.I am interested in data analysis. therefore i have good skill in excel, SQL query, vba and PowerBI.Besides I have knowledge about Camera system, hardware system, network system ."
var story = 
"Passion for information technology (IT) is a driving force that fuels individuals to explore, innovate, and excel in the dynamic world of technology. At its core, IT passion is an unwavering commitment to understanding and leveraging the power of digital tools to solve complex problems, enhance efficiency, and propel progress across various industries.Those with a fervor for IT often find joy in the continuous evolution of the field. The rapid advancements in hardware, software, and networking technologies present an ever-expanding canvas for exploration. Enthusiasts revel in the challenge of staying abreast of the latest trends, eagerly immersing themselves in the intricacies of emerging technologies like artificial intelligence, blockchain, and the Internet of Things.A passion for IT is characterized by an insatiable curiosity. IT enthusiasts are driven to dissect and understand the inner workings of systems, software, and algorithms. This curiosity extends beyond the surface level, propelling individuals to delve into the intricacies of coding languages, cybersecurity protocols, and data analytics methodologies. The joy derived from unraveling the complexities of technology becomes a motivating force that propels individuals to refine their skills continually.Moreover, the IT passionate are often natural problem solvers. They relish the opportunity to apply their technical acumen to address real-world challenges. Whether it's streamlining business processes, developing innovative applications, or fortifying cybersecurity measures, the IT enthusiast thrives on the tangible impact their skills can have on society.In a world increasingly shaped by digital transformation, the importance of IT passion cannot be overstated. It is the catalyst for innovation, the driving force behind technological breakthroughs, and the key to unlocking the full potential of the digital age. As the technological landscape continues to evolve, those with a genuine passion for information technology will remain at the forefront, shaping the future through their creativity, ingenuity, and unwavering commitment to the possibilities that technology offers.";
var pluslink=
"https://vietnam.travel/sites/default/files/styles/top_banner/public/2017-08/best-pho-in-vietnam.jpg?itok=IOnKltTS^I like Pho^https://vietnam.travel/things-to-do/history-pho|https://vietnamtravel.com/images/2020/12/bun-cha-a-tasty-dish-thumbnail.jpg^And I like bun cha,too^https://vietnamtravel.com/bun-cha/";

/*
lưu ý: viết trên một dòng
avatar copy đường dẫn vào là ok
introducce nội dung xuống dòng bằng dấu .
story nội dung xuống dòng bằng dấu .
pluslink ảnh1^nội dung1^đường dẫn1|ảnh 2^nội dung2^đường dẫn2 ....
*/
